# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from freeclimb.models.percl_command import PerclCommand
from pydantic import StrictStr
from typing import Optional, Set
from typing_extensions import Self


class AudioStream(
    PerclCommand,
    populate_by_name=True,
    validate_assignment=True,
    protected_namespaces=(),
):
    """
    The `AudioStream` command transfers control of the call to a gRPC session.  Upon completion of the gRPC session, if the actionUrl is specified, control can be returned to percl usage or the call will simply be hung up if the actionUrl is not specified.
    """  # noqa: E501

    location: StrictStr = Field(
        description="The gRPC server location that will receive the grpc stream as a uri and must be port 80 or 443."
    )
    action_url: Optional[StrictStr] = Field(
        default=None,
        description="A request is made to this URL when the gRPC session is concluded. The PerCL script returned in response to the actionUrl will be executed on the call.",
        alias="actionUrl",
    )
    content_type: Optional[StrictStr] = Field(
        default=None,
        description="The type and sample rate of the audio being received over the channel must match the environmental sample rate.",
        alias="contentType",
    )
    meta_data: Optional[List[StrictStr]] = Field(
        default=None,
        description="An arbitrary array of strings passed through FC to the GRPC server can be used to pass state or other information about the call.",
        alias="metaData",
    )
    privacy_mode: Optional[StrictBool] = Field(
        default=None,
        description="Enables audio redaction with full call recording while gRPC session is running and blocks logging of any DTMFs received by FreeClimb.",
        alias="privacyMode",
    )
    command: StrictStr = "AudioStream"

    __properties: ClassVar[List[str]] = [
        "command",
        "location",
        "actionUrl",
        "contentType",
        "metaData",
        "privacyMode",
    ]

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AudioStream from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AudioStream from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "command": obj.get("command"),
                "location": obj.get("location"),
                "actionUrl": obj.get("actionUrl"),
                "contentType": obj.get("contentType"),
                "metaData": obj.get("metaData"),
                "privacyMode": obj.get("privacyMode"),
            }
        )
        return _obj
