# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Language(str, Enum):
    """
    Language
    """

    """
    allowed enum values
    """
    CA_MINUS_ES = 'ca-ES'
    DA_MINUS_DK = 'da-DK'
    DE_MINUS_DE = 'de-DE'
    EN_MINUS_AU = 'en-AU'
    EN_MINUS_CA = 'en-CA'
    EN_MINUS_GB = 'en-GB'
    EN_MINUS_IN = 'en-IN'
    EN_MINUS_US = 'en-US'
    ES_MINUS_ES = 'es-ES'
    ES_MINUS_MX = 'es-MX'
    FI_MINUS_FI = 'fi-FI'
    FR_MINUS_CA = 'fr-CA'
    FR_MINUS_FR = 'fr-FR'
    IT_MINUS_IT = 'it-IT'
    JA_MINUS_JP = 'ja-JP'
    KO_MINUS_KR = 'ko-KR'
    NB_MINUS_NO = 'nb-NO'
    NL_MINUS_NL = 'nl-NL'
    PL_MINUS_PL = 'pl-PL'
    PT_MINUS_BR = 'pt-BR'
    PT_MINUS_PT = 'pt-PT'
    RU_MINUS_RU = 'ru-RU'
    SV_MINUS_SE = 'sv-SE'
    ZH_MINUS_CN = 'zh-CN'
    ZH_MINUS_HK = 'zh-HK'
    ZH_MINUS_TW = 'zh-TW'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Language from a JSON string"""
        return cls(json.loads(json_str))


