# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freeclimb.models.transcribe_utterance_all_of_record import TranscribeUtteranceAllOfRecord

class TestTranscribeUtteranceAllOfRecord(unittest.TestCase):
    """TranscribeUtteranceAllOfRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranscribeUtteranceAllOfRecord:
        """Test TranscribeUtteranceAllOfRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranscribeUtteranceAllOfRecord`
        """
        model = TranscribeUtteranceAllOfRecord()
        if include_optional:
            return TranscribeUtteranceAllOfRecord(
                save_recording = True,
                max_length_sec = 1,
                rcrd_termination_silence_time_ms = 0
            )
        else:
            return TranscribeUtteranceAllOfRecord(
        )
        """

    def testTranscribeUtteranceAllOfRecord(self):
        """Test TranscribeUtteranceAllOfRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
