# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freeclimb.models.sms_ten_dlc_partner_campaign_brand import SMSTenDLCPartnerCampaignBrand

class TestSMSTenDLCPartnerCampaignBrand(unittest.TestCase):
    """SMSTenDLCPartnerCampaignBrand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SMSTenDLCPartnerCampaignBrand:
        """Test SMSTenDLCPartnerCampaignBrand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SMSTenDLCPartnerCampaignBrand`
        """
        model = SMSTenDLCPartnerCampaignBrand()
        if include_optional:
            return SMSTenDLCPartnerCampaignBrand(
                account_id = '',
                brand_id = '',
                first_name = 'John',
                last_name = 'Doe',
                display_name = 'ABC Mobile',
                company_name = 'ABC Inc.',
                phone = '+12024567890',
                email = '',
                website = 'http://www.abcmobile.com',
                optional_attributes = {
                    'key' : None
                    },
                evp_vetting_score = 56
            )
        else:
            return SMSTenDLCPartnerCampaignBrand(
                phone = '+12024567890',
                email = '',
        )
        """

    def testSMSTenDLCPartnerCampaignBrand(self):
        """Test SMSTenDLCPartnerCampaignBrand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
