# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freeclimb.models.sms_ten_dlc_partner_campaign import SMSTenDLCPartnerCampaign

class TestSMSTenDLCPartnerCampaign(unittest.TestCase):
    """SMSTenDLCPartnerCampaign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SMSTenDLCPartnerCampaign:
        """Test SMSTenDLCPartnerCampaign
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SMSTenDLCPartnerCampaign`
        """
        model = SMSTenDLCPartnerCampaign()
        if include_optional:
            return SMSTenDLCPartnerCampaign(
                account_id = '',
                campaign_id = '',
                status = 'ACTIVE',
                create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                brand_id = '',
                usecase = '',
                description = '',
                embedded_link = True,
                embedded_phone = True,
                affiliate_marketing = True,
                number_pool = True,
                age_gated = True,
                direct_lending = True,
                subscriber_optin = True,
                subscriber_optout = True,
                subscriber_help = True,
                sample1 = '',
                sample2 = '',
                sample3 = '',
                sample4 = '',
                sample5 = '',
                message_flow = '',
                help_message = '',
                optin_keywords = '',
                optout_keywords = '',
                help_keywords = '',
                optin_message = '',
                optout_message = '',
                brand = freeclimb.models.sms_ten_dlc_partner_campaign_brand.SMSTenDLCPartnerCampaignBrand(
                    account_id = '', 
                    brand_id = '', 
                    first_name = 'John', 
                    last_name = 'Doe', 
                    display_name = 'ABC Mobile', 
                    company_name = 'ABC Inc.', 
                    phone = '+12024567890', 
                    email = '', 
                    website = 'http://www.abcmobile.com', 
                    optional_attributes = {
                        'key' : None
                        }, 
                    evp_vetting_score = 56, )
            )
        else:
            return SMSTenDLCPartnerCampaign(
                campaign_id = '',
                brand_id = '',
                usecase = '',
                description = '',
        )
        """

    def testSMSTenDLCPartnerCampaign(self):
        """Test SMSTenDLCPartnerCampaign"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
