# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import pydantic_core
from datetime import datetime
import freeclimb
from freeclimb import *
from freeclimb.models.create_blob_request import CreateBlobRequest


class TestCreateBlobRequest(unittest.TestCase):
    """CreateBlobRequest unit test stubs"""

    def setUp(self):
        self.model = CreateBlobRequest(
            blob={},
        )

    def test_alias(self):
        """Test CreateBlobRequest.alias"""
        self.model.alias = "T" * 64
        assert self.model.alias == "T" * 64

        with self.assertRaises(pydantic_core._pydantic_core.ValidationError) as info:
            self.model.alias = "T" * (64 + 1)

    def test_expires_at(self):
        """Test CreateBlobRequest.expires_at"""

        self.model.expires_at = "TEST_STRING"
        assert self.model.expires_at == "TEST_STRING"

    def test_blob(self):
        """Test CreateBlobRequest.blob"""
        object = {}
        self.model.blob = object
        assert self.model.blob == object


if __name__ == "__main__":
    unittest.main()
