# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import pydantic_core
from datetime import datetime
import freeclimb
from freeclimb import *
from freeclimb.models.platform_error import PlatformError


class TestPlatformError(unittest.TestCase):
    """PlatformError unit test stubs"""

    def setUp(self):
        self.model = PlatformError()

    def test_code(self):
        """Test PlatformError.code"""
        self.model.code = 1
        assert self.model.code == 1

    def test_call(self):
        """Test PlatformError.call"""

        self.model.call = "TEST_STRING"
        assert self.model.call == "TEST_STRING"

    def test_url(self):
        """Test PlatformError.url"""

        self.model.url = "TEST_STRING"
        assert self.model.url == "TEST_STRING"

    def test_details(self):
        """Test PlatformError.details"""
        object = {}
        self.model.details = object
        assert self.model.details == object


if __name__ == "__main__":
    unittest.main()
