# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freeclimb.models.queue_wait_webhook import QueueWaitWebhook

class TestQueueWaitWebhook(unittest.TestCase):
    """QueueWaitWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueueWaitWebhook:
        """Test QueueWaitWebhook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueueWaitWebhook`
        """
        model = QueueWaitWebhook()
        if include_optional:
            return QueueWaitWebhook(
                request_type = '',
                account_id = '',
                call_id = '',
                var_from = '',
                to = '',
                call_status = 'queued',
                direction = 'inbound',
                conference_id = '',
                queue_id = '',
                queue_position = '',
                queue_time = 56,
                current_queue_size = 56
            )
        else:
            return QueueWaitWebhook(
        )
        """

    def testQueueWaitWebhook(self):
        """Test QueueWaitWebhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
