# coding: utf-8

"""
    FreeClimb API

    FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

    The version of the OpenAPI document: 1.0.0
    Contact: support@freeclimb.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freeclimb.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_buy_a_phone_number(self) -> None:
        """Test case for buy_a_phone_number

        Buy a Phone Number
        """
        pass

    def test_create_a_conference(self) -> None:
        """Test case for create_a_conference

        Create a Conference
        """
        pass

    def test_create_a_queue(self) -> None:
        """Test case for create_a_queue

        Create a Queue
        """
        pass

    def test_create_an_application(self) -> None:
        """Test case for create_an_application

        Create an application
        """
        pass

    def test_create_knowledge_base_completion(self) -> None:
        """Test case for create_knowledge_base_completion

        Query the knowledge base
        """
        pass

    def test_delete_a_recording(self) -> None:
        """Test case for delete_a_recording

        Delete a Recording
        """
        pass

    def test_delete_an_application(self) -> None:
        """Test case for delete_an_application

        Delete an application
        """
        pass

    def test_delete_an_incoming_number(self) -> None:
        """Test case for delete_an_incoming_number

        Delete an Incoming Number
        """
        pass

    def test_dequeue_a_member(self) -> None:
        """Test case for dequeue_a_member

        Dequeue a Member
        """
        pass

    def test_dequeue_head_member(self) -> None:
        """Test case for dequeue_head_member

        Dequeue Head Member
        """
        pass

    def test_download_a_recording_file(self) -> None:
        """Test case for download_a_recording_file

        Download a Recording File
        """
        pass

    def test_filter_logs(self) -> None:
        """Test case for filter_logs

        Filter Logs
        """
        pass

    def test_get_a_call(self) -> None:
        """Test case for get_a_call

        Get a Call
        """
        pass

    def test_get_a_conference(self) -> None:
        """Test case for get_a_conference

        Get a Conference
        """
        pass

    def test_get_a_member(self) -> None:
        """Test case for get_a_member

        Get a Member
        """
        pass

    def test_get_a_participant(self) -> None:
        """Test case for get_a_participant

        Get a Participant
        """
        pass

    def test_get_a_queue(self) -> None:
        """Test case for get_a_queue

        Get a Queue
        """
        pass

    def test_get_a_recording(self) -> None:
        """Test case for get_a_recording

        Get a Recording
        """
        pass

    def test_get_an_account(self) -> None:
        """Test case for get_an_account

        Get an Account
        """
        pass

    def test_get_an_application(self) -> None:
        """Test case for get_an_application

        Get an Application
        """
        pass

    def test_get_an_incoming_number(self) -> None:
        """Test case for get_an_incoming_number

        Get an Incoming Number
        """
        pass

    def test_get_an_sms_message(self) -> None:
        """Test case for get_an_sms_message

        Get an SMS Message
        """
        pass

    def test_get_head_member(self) -> None:
        """Test case for get_head_member

        Get Head Member
        """
        pass

    def test_get_ten_dlc_sms_brand(self) -> None:
        """Test case for get_ten_dlc_sms_brand

        Get a 10DLC SMS Brand
        """
        pass

    def test_get_ten_dlc_sms_brands(self) -> None:
        """Test case for get_ten_dlc_sms_brands

        Get list of SMS 10DLC Brands
        """
        pass

    def test_get_ten_dlc_sms_campaign(self) -> None:
        """Test case for get_ten_dlc_sms_campaign

        Get a 10DLC SMS Campaign
        """
        pass

    def test_get_ten_dlc_sms_campaigns(self) -> None:
        """Test case for get_ten_dlc_sms_campaigns

        Get list of SMS 10DLC Campaigns
        """
        pass

    def test_get_ten_dlc_sms_partner_campaign(self) -> None:
        """Test case for get_ten_dlc_sms_partner_campaign

        Get a 10DLC SMS Partner Campaign
        """
        pass

    def test_get_ten_dlc_sms_partner_campaigns(self) -> None:
        """Test case for get_ten_dlc_sms_partner_campaigns

        Get list of SMS 10DLC Partner Campaigns
        """
        pass

    def test_get_toll_free_sms_campaign(self) -> None:
        """Test case for get_toll_free_sms_campaign

        Get a TollFree SMS Campaign
        """
        pass

    def test_get_toll_free_sms_campaigns(self) -> None:
        """Test case for get_toll_free_sms_campaigns

        Get list of TollFree Campaigns
        """
        pass

    def test_list_active_queues(self) -> None:
        """Test case for list_active_queues

        List Active Queues
        """
        pass

    def test_list_all_account_logs(self) -> None:
        """Test case for list_all_account_logs

        List All Account Logs
        """
        pass

    def test_list_applications(self) -> None:
        """Test case for list_applications

        List applications
        """
        pass

    def test_list_available_numbers(self) -> None:
        """Test case for list_available_numbers

        List available numbers
        """
        pass

    def test_list_call_logs(self) -> None:
        """Test case for list_call_logs

        List Call Logs
        """
        pass

    def test_list_call_recordings(self) -> None:
        """Test case for list_call_recordings

        List Call Recordings
        """
        pass

    def test_list_calls(self) -> None:
        """Test case for list_calls

        List Calls
        """
        pass

    def test_list_conference_recordings(self) -> None:
        """Test case for list_conference_recordings

        List Conference Recordings
        """
        pass

    def test_list_conferences(self) -> None:
        """Test case for list_conferences

        List Conferences
        """
        pass

    def test_list_incoming_numbers(self) -> None:
        """Test case for list_incoming_numbers

        List Incoming Numbers
        """
        pass

    def test_list_members(self) -> None:
        """Test case for list_members

        List Members
        """
        pass

    def test_list_participants(self) -> None:
        """Test case for list_participants

        List Participants
        """
        pass

    def test_list_recordings(self) -> None:
        """Test case for list_recordings

        List Recordings
        """
        pass

    def test_list_sms_messages(self) -> None:
        """Test case for list_sms_messages

        List SMS Messages
        """
        pass

    def test_make_a_call(self) -> None:
        """Test case for make_a_call

        Make a Call
        """
        pass

    def test_make_a_webrtc_jwt(self) -> None:
        """Test case for make_a_webrtc_jwt

        Make a JWT for WebRTC calling
        """
        pass

    def test_remove_a_participant(self) -> None:
        """Test case for remove_a_participant

        Remove a Participant
        """
        pass

    def test_send_an_sms_message(self) -> None:
        """Test case for send_an_sms_message

        Send an SMS Message
        """
        pass

    def test_stream_a_recording_file(self) -> None:
        """Test case for stream_a_recording_file

        Stream a Recording File
        """
        pass

    def test_update_a_conference(self) -> None:
        """Test case for update_a_conference

        Update a Conference
        """
        pass

    def test_update_a_live_call(self) -> None:
        """Test case for update_a_live_call

        Update a Live Call
        """
        pass

    def test_update_a_participant(self) -> None:
        """Test case for update_a_participant

        Update a Participant
        """
        pass

    def test_update_a_queue(self) -> None:
        """Test case for update_a_queue

        Update a Queue
        """
        pass

    def test_update_an_account(self) -> None:
        """Test case for update_an_account

        Manage an account
        """
        pass

    def test_update_an_application(self) -> None:
        """Test case for update_an_application

        Update an application
        """
        pass

    def test_update_an_incoming_number(self) -> None:
        """Test case for update_an_incoming_number

        Update an Incoming Number
        """
        pass


if __name__ == '__main__':
    unittest.main()
